#!/usr/bin/env python3
##
## PERSONNAL PROJECT, 2023
## Trade bot with Bitcoin
## File description:
## main
##

from sys import stderr, argv
from Bot.Bot import Bot
from server.Server import Server
from json import load

def description():
    print("DESCRIPTION")
    print("\tAlgo to trade automatically some crypto")
    print("USAGE")
    print("\t./run.sh")

if __name__ == '__main__':
    if len(argv) == 2 and argv[1] == '-h':
        description()
        exit(0)
    if len(argv) >= 2:
        print(f'Bad number of args; -h for help', flush=True, file=stderr)
        exit(-1)
    conf = load(open('data/value.json', 'r', encoding='utf-8'))
    mybot = Bot(conf)
    myserver = Server(conf, mybot)
    print(f'loading...', flush=True)
    myserver.graph.run()
